package main

// DO NOT EDIT, this file is generated by hover at compile-time for the go_flutter_plugin_serial plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	go_flutter_plugin_serial "github.com/chenhuawei/go-flutter-plugin-serial/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&go_flutter_plugin_serial.GoFlutterPluginSerialPlugin{}))
}
